env:
  global:
  - secure: "xWpnLfm52RrsFicUdY+WBkbNCYJTn+h6j5jsTLMrFof1OKuCscwrTY8xz5ush5cjsjwAZ+hxqd43CkBTu19QsPrEIzjPog7QA77gNxnf95uqy0rZ2Uv4DgxCFrr+v/Jg7KaQvmXStWRjEj38vLkDjcIsVsz6jEOVqCPJ/A1rHBxjum9vdgZTRi5xOkI5JlRk/9wg4Z5UG4ngt1ZJjWZ1OSMcLr2r4gKntKWHLFHSLcStVHx9ObtiO9UJda9W6czT5RJNHx5eJd6woWMhKuYCilgsOsHRb99fg1OgCCeMFh5dqzg1Ss1w+MonaP5lrStZbunqZ3xeBnAd79XVlKTYkJ6qfNIT+AzqZpVL4jF/v5A7WrCAu1RiAl4Tz7n5G4xVnj0fqZ+g9bekMj+S3Z72bv0raeYa6/gyri0lb3WqC1oWKLvgNLIhcaADP7rVf52inzuUDZASVmdbWSHvlefvvD985mvMfn2VOi32XLpiLIpCm2tCy6/yj3k7zHCzncoVTmOITWiX4QuEyDL74XGmcbpmz2G3rlGzLY9yB+aRNraMGi71zM/KZrCJFXgAbyiqo1NrOKB3A4+WP7FNocvhklDLhC3RlKluGCQw+O7M2qn/WRn6FNhSQBDs0ZK05dCI4j3Lt7w/ZCZKvIdn0AWQLc9NmFQ0g+rF5AD7HTUNdtY="
  - secure: "qntJuZqbwqQIscPgTtlBlkYkOGiell+Wolr6iHfLNfVz5ghHNHbNw/d77GAHxx4LMYYeK87Y7c8Z9UBcZJaY1SzSXCbOLMiX3NiaVrNcFhE/3loc9iTlJWQ4HCZyFmn/7XfrtGugMxq5Vn7ndtCHpiaUbL4MJMrvOj6SOpxRjvB0/8Mlz6d3laVtEMs6CkL2k5zDLIZKu0LonCrAifjh08D8BVhVWPIJGT+Fu1aU5v7/Dw2fTD5U8fWSq9ZNylKms0VLnXT8wZA8AUCIlyuOJk5UB2qhRVlIFkmsjgEOrCDLtQfqs4Get6x/rM9H82Bw9UOGvjg7nr7uDm1QyXg1wuJCV3dCQS5dXy3y9yFq6Ttifs4882kyZy2fFcVI6ManxMF63G8J6Rc5sgPvv1XpdxkhPdCI9mJmj5fyXZzzVaO3lSkE/nJ0uDwGnCZu8zQsA+sIrudyfo5t7l9j2k1zGIHH8nDxITkN4MkKb1SosQ1yuCRuLGtWfA492VEWv/6YWgaOLGs38EXIlr3meScquqXnl2B/LoAHrsIi5PSu5BZAn35weXxaj/9I5I1l369F09OsWPTekpQv6Agpr1zxPPMUHIXIJ7HdUPwRxm3qehaH2xwFk3r5zTWD0edyUcRGTnnHIA2kJnYu2yp1nG+06Bo3OGXfbPGgov0Fg+85PF8="

dist: xenial

language: python
python:
- "3.5"

addons:
  postgresql: "9.6"
  apt:
    update: true
    packages:
    - postgresql-9.6-plv8
    - libgnutls28-dev
cache:
  pip: true

before_install:
# travis django settings
- cd capstone
- cp config/settings/settings_travis.py config/settings/settings.py

# set up postgres
- sudo sh -c "echo shared_preload_libraries = 'pg_stat_statements' >> /etc/postgresql/9.6/main/postgresql.conf"
- sudo /etc/init.d/postgresql restart
- sudo rm -f /etc/boto.cfg

# set up node
- nvm install 11.14.0
- nvm use 11.14.0

install:
# python packages
- pip install -U pip wheel
- pip install -r requirements.txt
- pip install coveralls

# node packages
- npm install

before_script:
- python manage.py collectstatic --noinput
  
script:
- fab test

after_success:
- coveralls
- >
  if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "develop" ] ;
  then
  export DEPLOY_CONTENT='{"TRAVIS_BUILD_NUMBER":"'$TRAVIS_BUILD_NUMBER'","TRAVIS_COMMIT":"'$TRAVIS_COMMIT'","TRAVIS_BRANCH":"'$TRAVIS_BRANCH'","TRAVIS_REPO_SLUG":"'$TRAVIS_REPO_SLUG'"}' ;
  export DEPLOY_SIG="sha1=`echo -n "$DEPLOY_CONTENT" | openssl sha1 -hmac $DEPLOY_KEY | sed 's/^.* //'`" ;
  curl -X POST "$DEPLOY_URL" --data "$DEPLOY_CONTENT" -H "Content-Type: application/json" -H "X-Travis-Signature: $DEPLOY_SIG" ;
  fi

after_failure:
- git diff
